### ISSUE TITLE
The platform files repo is inaccessible

### ISSUE THREAD

**Issue by ZhekaS** [synapticon/SOMANET-OS#1]
The referenced module repo SOMANET-platform-files is inaccessible.

**Comment by agus-xyz** [comment]
Solved problem with the repo access rights.
It is accessible now.
Close the issue.
Thanks a lot!!
best.

**Comment by agus-xyz** [comment]
In any case, all the platform files are available at sc_somanet-base.
The SOMANET-platform-files repo will be removed soon.
